title: Amanda White # your name (or website title) here
logo: "/Users/amandawhite/Downloads/Headshot.jpeg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Fourth Year Business Analytics Student 
  <br><br>
  Miami University Research and Teaching Assistant
  <br><br>
  <a href="https://www.linkedin.com/in/amanda-white123/">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: G-DB6DX5192G # your Google Analytics tracking ID here
